stages:
  - compile
  - verify
  - package
  - publish

default:
  image: ${REGISTRY_HOST}/${REGISTRY_NS_TOOLS}/gradle:8.8.0-jdk17-jammy
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/
  interruptible: true

compile:
  stage: compile
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/cache"
  script:
    - ./gradlew classes testClasses --build-cache
  cache:
    policy: pull-push
  artifacts:
    paths:
      - "**/build/classes/"
      - "**/build/resources/"
      - "**/build/generated/"
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "dev"

unit-tests:
  stage: verify
  needs: [compile]
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/cache"
  script:
    - ./gradlew test --build-cache --init-script unit-tests.gradle
  cache:
    policy: pull
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "dev"

integration-tests:
  stage: verify
  needs: [compile]
  services:
    - name: ${REGISTRY_DIND_IMAGE}
      alias: docker
      command: ["--tls=false"]
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/cache"
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - ./gradlew test --build-cache --init-script integration-tests.gradle
  cache:
    policy: pull
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "dev"

shadow-jar:
  stage: package
  needs: [compile]
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/cache"
  script:
    - ./gradlew shadowJar --build-cache
  cache:
    policy: pull
  artifacts:
    paths:
      - "**/build/libs/*.jar"
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "dev"

docker-build-push:
  stage: publish
  services:
    - name: ${REGISTRY_DIND_IMAGE}
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_CONFIG: "./gradle"
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/cache"
  cache:
    policy: pull
  needs:
    - job: unit-tests
    - job: integration-tests
    - job: shadow-jar
      artifacts: true
  script:
    - ./build.sh
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "dev"
