stages:
  - test
  - build

default:
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/

unit-tests:
  stage: test
  image: ${REGISTRY_HOST}/${REGISTRY_NS_TOOLS}/gradle:8.8.0-jdk17-jammy
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/cache"
  script:
    - ./gradlew test -I init-ci.gradle
  cache:
    policy: pull-push
  artifacts:
    when: always
    paths:
      - "**/build/reports/tests/"
    reports:
      junit:
        - "**/build/test-results/test/TEST-*.xml"
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "dev"

build:
  stage: build
  services:
    - name: ${REGISTRY_DIND_IMAGE}
      alias: docker
      command: [ "--tls=false" ]
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_CONFIG: "./gradle"
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/cache"
  cache:
    policy: pull
  needs:
    - job: unit-tests
      optional: true
#  artifacts:
#    paths:
#      - launchers/control-plane/control-plane-postgresql-hashicorpvault/build/libs/*.jar
#    expire_in: 30 days
#    when: always
  image:  ${REGISTRY_HOST}/${REGISTRY_NS_TOOLS}/gradle:8.8.0-jdk17-jammy
  script:
#    - ./gradlew :launchers:control-plane:control-plane-postgresql-hashicorpvault:shadowJar
    - ./build.sh
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
    - if: $CI_COMMIT_REF_NAME == "dev"
  interruptible: true
