openapi: 3.0.1
info:
  description: This API is used to manipulate domain attestations
  title: Issuer Service Domain Attestation API
  version: "1"
security:
- bearerAuth: []
- apiKeyAuth: []
paths:
  /v1alpha/participants/{participantContextId}/attestation-domain:
    post:
      description: Adds a new domain attestation.
      operationId: createDomainAttestation
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DomainAttestation"
      responses:
        "204":
          description: The domain attestation was added successfully.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "409":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Can't add the domain attestation, because a object with the\
            \ same ID already exists"
      tags:
      - Domain Attestation Admin API
    put:
      description: Updates domain attestation.
      operationId: updateDomainAttestation
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DomainAttestation"
      responses:
        "204":
          description: The domain attestation was updated successfully.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "The request could not be completed, because either the authentication\
            \ was missing or was not valid."
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: Can't update the domain attestation because it was not found.
      tags:
      - Domain Attestation Admin API
  /v1alpha/participants/{participantContextId}/attestation-domain/request:
    post:
      description: Gets all domain attestations for a certain query.
      operationId: queryDomainAttestations
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuerySpec"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DomainAttestation"
          description: A list of domain attestations metadata.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
      tags:
      - Domain Attestation Admin API
  /v1alpha/participants/{participantContextId}/attestation-domain/{id}:
    delete:
      description: Delete domain attestation.
      operationId: deleteDomainAttestation
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "204":
          description: The domain attestation was deleted successfully.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: Can't delete domain attestation because it was not found.
      tags:
      - Domain Attestation Admin API
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: object
        message:
          type: string
        path:
          type: string
        type:
          type: string
    Criterion:
      type: object
      properties:
        operandLeft:
          type: object
        operandRight:
          type: object
        operator:
          type: string
    DomainAttestation:
      type: object
      properties:
        domain:
          type: string
        holderId:
          type: string
        id:
          type: string
    DomainAttestationDto:
      type: object
      properties:
        domain:
          type: string
        holderId:
          type: string
        id:
          type: string
    QuerySpec:
      type: object
      properties:
        filterExpression:
          type: array
          items:
            $ref: "#/components/schemas/Criterion"
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        sortField:
          type: string
        sortOrder:
          type: string
          enum:
          - ASC
          - DESC
  securitySchemes:
    apiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
