apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-proxy.labels" . | nindent 4 }}
    {{- if .Values.kafkaProxy.proxy.service.enabled }}
    {{- toYaml .Values.kafkaProxy.proxy.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.kafkaProxy.proxy.service.enabled | ternary .Values.kafkaProxy.proxy.service.type .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementTargetPort }}
      protocol: TCP
      name: management
  selector:
    {{- include "kafka-proxy.selectorLabels" . | nindent 4 }}